services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: gamesMVC
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gamesdb
      SPRING_DATASOURCE_USERNAME: gamemaster
      SPRING_DATASOURCE_PASSWORD: crazydiamondo
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"

  db:
    image: postgres:16
    container_name: games-postgres-db
    environment:
      POSTGRES_DB: gamesdb
      POSTGRES_USER: gamemaster
      POSTGRES_PASSWORD: crazydiamondo
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: