CREATE TABLE account_type
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_account_type PRIMARY KEY (id)
);

CREATE TABLE game
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255),
    description  VARCHAR(255),
    release_date date,
    like_number  INTEGER                                 NOT NULL,
    CONSTRAINT pk_game PRIMARY KEY (id)
);

CREATE TABLE genre
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_genre PRIMARY KEY (id)
);

CREATE TABLE genre_game
(
    game_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT pk_genre_game PRIMARY KEY (game_id, genre_id)
);

CREATE TABLE likes
(
    game_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (game_id, user_id)
);

CREATE TABLE studio
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_studio PRIMARY KEY (id)
);

CREATE TABLE studio_game
(
    game_id   BIGINT NOT NULL,
    studio_id BIGINT NOT NULL,
    CONSTRAINT pk_studio_game PRIMARY KEY (game_id, studio_id)
);

CREATE TABLE users
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username        VARCHAR(255),
    email           VARCHAR(255),
    password        VARCHAR(255),
    account_type_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ACCOUNT_TYPE FOREIGN KEY (account_type_id) REFERENCES account_type (id);

ALTER TABLE genre_game
    ADD CONSTRAINT fk_gengam_on_game FOREIGN KEY (game_id) REFERENCES game (id);

ALTER TABLE genre_game
    ADD CONSTRAINT fk_gengam_on_genre FOREIGN KEY (genre_id) REFERENCES genre (id);

ALTER TABLE likes
    ADD CONSTRAINT fk_likes_on_game FOREIGN KEY (game_id) REFERENCES game (id);

ALTER TABLE likes
    ADD CONSTRAINT fk_likes_on_users FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE studio_game
    ADD CONSTRAINT fk_stugam_on_game FOREIGN KEY (game_id) REFERENCES game (id);

ALTER TABLE studio_game
    ADD CONSTRAINT fk_stugam_on_studio FOREIGN KEY (studio_id) REFERENCES studio (id);